/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_daal_algorithms_ModelSerializer */

#ifndef _Included_com_intel_daal_algorithms_ModelSerializer
#define _Included_com_intel_daal_algorithms_ModelSerializer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_daal_algorithms_ModelSerializer
 * Method:    cSerializeQrModel
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_intel_daal_algorithms_ModelSerializer_cSerializeQrModel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_daal_algorithms_ModelSerializer
 * Method:    cDeserializeQrModel
 * Signature: (Ljava/nio/ByteBuffer;J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_daal_algorithms_ModelSerializer_cDeserializeQrModel
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_intel_daal_algorithms_ModelSerializer
 * Method:    cFreeByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_algorithms_ModelSerializer_cFreeByteBuffer
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
