/**
 *  Copyright (c) 2015 Intel Corporation 
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */


package org.trustedanalytics.atk.domain.frame

import org.trustedanalytics.atk.engine.plugin.{ ArgDoc, Invocation }

case class AssignSampleArgs(frame: FrameReference,
                            @ArgDoc("""Entries are non-negative and sum to 1. (See the note below.)
If the *i*'th entry of the  list is *p*,
then then each row receives label *i* with independent probability *p*.""") samplePercentages: List[Double],
                            @ArgDoc("""Names to be used for the split classes.
Defaults to "TR", "TE", "VA" when the length of *sample_percentages* is 3,
and defaults to Sample_0, Sample_1, ... otherwise.""") sampleLabels: Option[List[String]] = None,
                            @ArgDoc("""Name of the new column which holds the labels generated by the
function.""") outputColumn: Option[String] = None,
                            @ArgDoc("""Random seed used to generate the labels.
Defaults to 0.""") randomSeed: Option[Int] = None) {
  require(frame != null, "AssignSample requires a non-null dataframe.")

  require(samplePercentages != null, "AssignSample requires that the percentages vector be non-null.")
  require(samplePercentages.nonEmpty, "AssignSample  requires that the percentages vector contain at least one value.")

  require(samplePercentages.forall(_ >= 0.0d), "AssignSample requires that all percentages be non-negative.")
  require(samplePercentages.forall(_ <= 1.0d), "AssignSample requires that all percentages be no more than 1.")

  def sumOfPercentages = samplePercentages.sum

  require(sumOfPercentages > 1.0d - 0.000000001,
    "AssignSample:  Sum of provided probabilities falls below one (" + sumOfPercentages + ")")
  require(sumOfPercentages < 1.0d + 0.000000001,
    "AssignSample:  Sum of provided probabilities exceeds one (" + sumOfPercentages + ")")

  def seed = randomSeed.getOrElse(0)
  def outputColumnName = outputColumn.getOrElse("sample_bin")

  def splitLabels: Array[String] = if (sampleLabels.isEmpty) {
    if (samplePercentages.length == 3) {
      Array("TR", "TE", "VA")
    }
    else {
      samplePercentages.indices.map(i => "Sample_" + i).toArray
    }
  }
  else {
    sampleLabels.get.toArray
  }
}
