#!/bin/bash

#
#trustedanalytics init script
#
#chkconfig: 345 99 25
#description: trustedanalytics analytics server for doing big data analytics
#

# Source function library.
. /etc/init.d/functions


prog=trustedanalytics-rest-server

checkBound(){
max=10
count=0

while [ $count -lt $max ];
do
    if [ -f /var/run/trustedanalytics-rest-server.pid ]; then
        PID=$(cat /var/run/trustedanalytics-rest-server.pid)
      else
        sleep 2
        continue
    fi
    for pid in `pstree -pn $PID | grep -o "[[:digit:]]*"`
    do
        bound=$(netstat -tulnp | grep $pid)
        if [ "$bound" != "" ]; then
            echo server is bound to port
            exit 0
        fi
    done
    sleep 2
    count=$((count+1))
done
}

initctlFunc() {
	local event=$1
	initctl $event $prog
	RETVAL=$?
	return $RETVAL
}


#change ownership log directory so logback has permissions to create application log
mkdir -p /var/log/trustedanalytics/rest-server
chown $TUSER:$TUSER /var/log/trustedanalytics/rest-server


# See how we were called.
case "$1" in
  start)
	initctlFunc start
	checkBound
	;;
  stop)
	initctlFunc stop
	;;
  status)
	initctlFunc status
	;;
  restart|force-reload)
	initctlFunc stop
	initctlFunc start
	checkBound
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|force-reload}"
	exit 2
esac
