/*
// Copyright (c) 2015 Intel Corporation 
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
*/

package org.trustedanalytics.atk.rest.v1.viewmodels

/**
 * The REST service response for single graph in "GET ../graphs/id"
 *
 * @param uri unique id auto-generated by the database
 * @param name name assigned by user
 * @param links links to related URIs
 */
case class GetGraph(uri: String, name: Option[String], links: List[RelLink], entityType: String, status: String) {
  require(uri != null, "uri must not be null")
  require(name != null, "name must not be null")
  require(links != null, "links must not be null")
  require(entityType != null, "entityType prefix must not be null")
  require(status != null, "status may not be null")
}
