/*
// Copyright (c) 2015 Intel Corporation 
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
*/

package org.trustedanalytics.atk.rest.v1.viewmodels

import org.trustedanalytics.atk.domain.Error
import spray.json.JsObject

/**
 * The REST service response for single command in "GET ../query/id"
 *
 * @param id unique id auto-generated by the database
 * @param name the name of the query to be performed. This name is purely for descriptive purposes.
 * @param arguments the arguments to the function. They are pulled directly from the QueryString
 * @param error StackTrace and/or other error text if it exists
 * @param complete True if this query is completed
 * @param result result of the query
 * @param links relevant links
 */
case class GetQuery(id: Option[Long], name: String, arguments: Option[JsObject], error: Option[Error],
                    complete: Boolean, result: Option[GetQueryPage], links: List[RelLink], correlationId: String = "") {
  require(name != null, "name must not be null")
  require(arguments != null, "arguments may not be null")
  require(links != null, "links may not be null")
  require(error != null, "error must not be null")
}
